apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mariadb
spec:
  secretName: mariadb-cert
  dnsNames:
  - mariadb.mariadb.svc.cluster.local
  - mariadb.mariadb.svc
  issuerRef:
    name: ss-issuer
    kind: Issuer
    group: cert-manager.io
